# Generated by Django 3.1.13 on 2021-11-05 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('fa_icon', models.CharField(default='code', max_length=100, verbose_name='FA icon')),
                ('source_link', models.CharField(blank=True, default='', max_length=255)),
                ('demo_link', models.CharField(blank=True, default='', max_length=255)),
                ('is_published', models.BooleanField()),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
