# Generated by Django 3.1.13 on 2021-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_tag_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fa_icon',
        ),
        migrations.AlterField(
            model_name='project',
            name='changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
