# Generated by Django 3.1.13 on 2021-11-10 17:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20211110_1751')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('is_published', models.BooleanField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
